# 1.4.12 Template Matching


In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
img_gray_mode = cv2.imread('soc3.png',0)

In [31]:
img_rgb = cv2.imread('soc3.png')
img_gray = cv2.cvtColor(img_rgb,cv2.COLOR_BGR2GRAY)

In [ ]:
cv2.imshow('img_gray_mode',img_gray_mode)
cv2.imshow('img_gray',img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
diff = cv2.bitwise_xor(img_gray, img_gray_mode)
img = cv2.imread('soc2.png',0)
img2 = img.copy()
template = cv2.imread('soc4.png',0)
w, h = template.shape[::-1]

# All the 6 methods for comparison in a list
methods = ['cv2.TM_CCOEFF', 'cv2.TM_CCOEFF_NORMED', 'cv2.TM_CCORR',
    'cv2.TM_CCORR_NORMED', 'cv2.TM_SQDIFF', 'cv2.TM_SQDIFF_NORMED']

In [ ]:
for meth in methods:
    img = img2.copy()
    method = eval(meth)
    # Apply template Matching
    res = cv2.matchTemplate(img,template,method)
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(res)
    # If the method is TM_SQDIFF or TM_SQDIFF_NORMED, take minimum
    if method in [cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED]:
        top_left = min_loc
    else:
        top_left = max_loc
    bottom_right = (top_left[0] + w, top_left[1] + h)
    cv2.rectangle(img,top_left, bottom_right, 255, 2)
    plt.figure(figsize=(20,15))
    plt.subplot(121),plt.imshow(res,cmap = 'gray')
    plt.title('Matching Result'), plt.xticks([]), plt.yticks([])
    plt.subplot(122),plt.imshow(img,cmap = 'gray')
    plt.title('Detected Point'), plt.xticks([]), plt.yticks([])
    plt.suptitle(meth)
    plt.show()

In [4]:
img_rgb = cv2.imread('mario.png')
img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY)
cv2.imshow('img_gray',img_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
template = cv2.imread('coin2.png',0)
cv2.imshow('coin2',template)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
w, h = template.shape[::-1]
print(w,h)

98 103


In [7]:
res = cv2.matchTemplate(img_gray, template, cv2.TM_CCOEFF_NORMED)

In [8]:
min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(res)
print(min_val, max_val, min_loc, max_loc)

-0.46095335483551025 0.5110791921615601 (1232, 183) (72, 798)


In [9]:
res=(res-min_val)/(max_val-min_val)
print(res)

[[0.43375805 0.45166218 0.46314722 ... 0.49986237 0.48786175 0.47840253]
 [0.42906016 0.4472195  0.45973727 ... 0.5000335  0.49095073 0.48417827]
 [0.4250269  0.44271892 0.45571262 ... 0.49861303 0.4925788  0.4882668 ]
 ...
 [0.5139079  0.5264291  0.53682333 ... 0.52771664 0.5564743  0.58401984]
 [0.5237908  0.53644717 0.5469793  ... 0.53394306 0.56270736 0.59011936]
 [0.5324447  0.5452098  0.5558086  ... 0.5398562  0.5685246  0.5957293 ]]


In [10]:
res = cv2.matchTemplate(img_gray,template,cv2.TM_CCOEFF_NORMED)
print(res)
cv2.imshow('img',res)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[-0.03932639 -0.02192301 -0.01075917 ...  0.02492913  0.01326414
   0.00406948]
 [-0.04389291 -0.02624146 -0.01407376 ...  0.02509546  0.01626674
   0.00968368]
 [-0.04781337 -0.03061618 -0.01798584 ...  0.02371475  0.01784926
   0.01365786]
 ...
 [ 0.03858186  0.05075287  0.06085642 ...  0.05200439  0.07995777
   0.10673294]
 [ 0.04818833  0.06049074  0.07072836 ...  0.05805664  0.08601652
   0.11266189]
 [ 0.05660022  0.06900835  0.07931074 ...  0.06380445  0.09167103
   0.1181149 ]]


In [23]:
threshold = 0.8
loc = np.where( res >= threshold)

In [24]:
print(loc[::-1])

(array([], dtype=int64), array([], dtype=int64))


In [25]:
img_rgb = cv2.imread('mario.png') #mario hmson2
for pt in zip(*loc[::-1]):
    cv2.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (255,0,255), 1)

In [26]:
cv2.imshow('dst',img_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
for pt in zip(*loc[::-1]):
    cv2.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (0,0,255), 2)
cv2.imshow('dst',img_rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()
    
cv2.imwrite('res.png',img_rgb)

True

In [28]:
def nothing(x):
    pass

In [33]:
cv2.namedWindow('image')
cv2.createTrackbar('threshold', 'image', 200, 255,nothing)
while(1):
    k = cv2.waitKey(1) & 0xFF
    if k == 27:
        break
    threshold = cv2.getTrackbarPos('threshold', 'image')
    loc = np.where(res >= threshold/255.)
    img_rgb = cv2.imread('mario_coin.png')
    for pt in zip(*loc[::-1]):
        cv2.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (255,0,255), 1)
    cv2.imshow('image',img_rgb)
cv2.destroyAllWindows()